export const getProducts = [
    {
        "id": 1,
        "title": "The Spiral Stool",
        "price": 319.95,
        "description": "The opening shape in the middle in this design consisting mainly of three helical plywood elements.",
        "category": "Stool",
        "image": require("../assets/images/1.jpeg"),
        "rating": {
        "rate": 6.9,
        "count": 120
        }
    },
    {
        "id": 2,
        "title": "The Wavelet",
        "price": 109.95,
        "description": "Quite a simple table design but the table top will surprise you. The plywood top bends on one side and therefore transforms into a smooth transport handle.",
        "category": "Tables",
        "image": require("../assets/images/2.jpeg"),
        "rating": {
        "rate": 3.9,
        "count": 120
        }
    },
    {
        "id": 3,
        "title": "The Laid-Back bookShelf",
        "price": 529.0,
        "description": "Not a unique design but I liked the design of the back support which I think is very minimalistic so that the whole design becomes very lightweight.",
        "category": "Bookshelves",
        "image": require("../assets/images/3.jpeg"),
        "rating": {
        "rate": 6.4,
        "count": 120
        }
    },
    {
        "id": 4,
        "title": "The Tie Stool",
        "price": 419.10,
        "description": "I like the unique shape of this stool consisting of three similar plywood elements. Like it or not it is definitely an eye-catching piece of furniture.",
        "category": "Stool",
        "image": require("../assets/images/4.jpeg"),
        "rating": {
        "rate": 8.4,
        "count": 120
        }
    },
    {
        "id": 5,
        "title": "The Monkey Stool",
        "price": 210.5,
        "description": "The shape of this stool consisting of three similar plywood elements is definitely an eye-catching piece of furniture.",
        "category": "Stool",
        "image": require("../assets/images/5.jpeg"),
        "rating": {
        "rate": 8.4,
        "count": 120
        }
    },
    {
        "id": 6,
        "title": "The Loop sideboard - bookrack",
        "price": 617.3,
        "description": "I just liked to design a playful piece of furniture like this once again. I think it would definitely be an eye-catcher in every kind of interior.",
        "category": "Bookshelves",
        "image": require("../assets/images/6.jpeg"),
        "rating": {
        "rate": 8.4,
        "count": 120
        }
    },
    {
        "id": 7,
        "title": "The Column side table",
        "price": 913.67,
        "description": "I just liked to design a playful piece of furniture like this once again. I think it would definitely be an eye-catcher in every kind of interior.",
        "category": "Side Tables",
        "image": require("../assets/images/7.jpeg"),
        "rating": {
        "rate": 8.4,
        "count": 120
        }
    },
    {
        "id": 8,
        "title": "The Bridge coffee Table",
        "price": 617.3,
        "description": "I like the simpleness of this deisgn. The wooden element is not only the supporting element but offers also an additional level for putting and highlighting items.",
        "category": "Coffee Table",
        "image": require("../assets/images/8.jpeg"),
        "rating": {
        "rate": 8.4,
        "count": 120
        }
    },
    {
        "id": 9,
        "title": "The Levels",
        "price": 645.23,
        "description": "This design consists of multiple layers of plywood where you can store books and documents in between and also in an unique cutout area.",
        "category": "Tables",
        "image": require("../assets/images/9.jpeg"),
        "rating": {
        "rate": 8.4,
        "count": 120
        }
    },
    {
        "id": 10,
        "title": "The Multangular side table - rack",
        "price": 617.3,
        "description": "A sculptural polygonal furniture able to serve as book storage and as a side table.",
        "category": "Side Tables",
        "image": require("../assets/images/10.jpeg"),
        "rating": {
        "rate": 8.4,
        "count": 120
        }
    },
    {
        "id": 11,
        "title": "The Cocoon coffee table",
        "price": 240.1,
        "description": "A shape generated by a flat plane were 2 edges are raised to generate a top level and a small gap to store items.",
        "category": "Coffee Table",
        "image": require("../assets/images/11.jpeg"),
        "rating": {
        "rate": 8.4,
        "count": 120
        }
    },
    {
        "id": 12,
        "title": "The Brute side table concept",
        "price": 617.3,
        "description": "A brutalist side table.",
        "category": "Side Tables",
        "image": require("../assets/images/12.jpeg"),
        "rating": {
        "rate": 8.4,
        "count": 120
        }
    },
    {
        "id": 13,
        "title": "The Tie tool",
        "price": 170.3,
        "description": "I like the unique shape of this stool consisting of three similar plywood elements. Like it or not it is definitely an eye-catching piece of furniture.",
        "category": "Tables",
        "image": require("../assets/images/13.jpeg"),
        "rating": {
        "rate": 8.4,
        "count": 120
        }
    },
    {
        "id": 14,
        "title": "The Kink side table",
        "price": 617.3,
        "description": "A single bent metal sheet which is supported by a wooden cylinder with a little 'Kink' on their intersection making the structure more stable and the overall design more exciting.",
        "category": "Side Tables",
        "image": require("../assets/images/14.jpeg"),
        "rating": {
        "rate": 8.4,
        "count": 120
        }
    },
    {
        "id": 15,
        "title": "The Melting Box",
        "price": 850.2,
        "description": "I like that the melting effect is not only visually appealing but also has a function here by generating extra storage areas.",
        "category": "Side Tables",
        "image": require("../assets/images/15.jpg"),
        "rating": {
        "rate": 8.4,
        "count": 120
        }
    },
    {
        "id": 16,
        "title": "The Shark Table",
        "price": 617.3,
        "description": "An amazing shark table made by plywood.",
        "category": "Tables",
        "image": require("../assets/images/16.jpeg"),
        "rating": {
        "rate": 8.4,
        "count": 120
        }
    },
    {
        "id": 17,
        "title": "The Curtain side table",
        "price": 47.3,
        "description": "A challenging plywood construction but definitely worth it I guess.",
        "category": "Side Tables",
        "image": require("../assets/images/17.jpeg"),
        "rating": {
        "rate": 8.4,
        "count": 120
        }
    },
    {
        "id": 18,
        "title": "The Circles Mirror",
        "price": 370.3,
        "description": "First look! A mirror which integrates a wall shel smoothly. Available for purchase soon!",
        "category": "Mirrors",
        "image": require("../assets/images/18.jpeg"),
        "rating": {
        "rate": 8.4,
        "count": 120
        }
    },
    {
        "id": 19,
        "title": "The Attraction low coffee table",
        "price": 617.3,
        "description": "I just liked to design a playful piece of furniture like this once again. I think it would definitely be an eye-catcher in every kind of interior.",
        "category": "Coffee Table",
        "image": require("../assets/images/19.jpeg"),
        "rating": {
        "rate": 8.4,
        "count": 120
        }
    },
    {
        "id": 20,
        "title": "The Sinuous Stool",
        "price": 380.1,
        "description": "A seemingly endless plywood sheet shapes this stoll which creates seating area and base support in one continuous twisted line.",
        "category": "Stool",
        "image": require("../assets/images/20.jpeg"),
        "rating": {
        "rate": 8.4,
        "count": 120
        }
    },
    {
        "id": 21,
        "title": "The Trinity Stool",
        "price": 449.2,
        "description": "I just love shapes consisting of three symmetrical elements! Furthermore, Trinity's legs have this special from allowing them to arrange perfectly together.",
        "category": "Stool",
        "image": require("../assets/images/21.jpeg"),
        "rating": {
        "rate": 8.4,
        "count": 120
        }
    },
    {
        "id": 22,
        "title": "The Sheets low coffee table",
        "price": 650.8,
        "description": "I like the idea of having multiple thin shaped plywood sheets arranged upon each other looking a stack of unsorted sheets of paper.",
        "category": "Coffee Table",
        "image": require("../assets/images/22.jpg"),
        "rating": {
        "rate": 8.4,
        "count": 120
        }
    },
    {
        "id": 23,
        "title": "The Crown Stool",
        "price": 330.3,
        "description": "Three identical solid wood elements arrange together to shape a very sculptural stool.",
        "category": "Stool",
        "image": require("../assets/images/23.jpeg"),
        "rating": {
        "rate": 8.4,
        "count": 120
        }
    },
    {
        "id": 24,
        "title": "The Bookscrew sideboard",
        "price": 780.55,
        "description": "I love the idea of a twisted sideboard to gain different access to your favourite books and highlight them in a special way due to the twisting metal frame.",
        "category": "Bookshelves",
        "image": require("../assets/images/24.jpeg"),
        "rating": {
        "rate": 8.4,
        "count": 120
        }
    },
    {
        "id": 25,
        "title": "The Pretzel table",
        "price": 280.99,
        "description": "Of course, as the name suggested already the design reminded me of the German bakery product of the same name.",
        "category": "Tables",
        "image": require("../assets/images/25.jpeg"),
        "rating": {
        "rate": 8.4,
        "count": 120
        }
    },
    {
        "id": 26,
        "title": "The Linked side table",
        "price": 230.3,
        "description": "Three interconnected cubes shaping multiple useful interspaces.",
        "category": "Side Tables",
        "image": require("../assets/images/26.jpeg"),
        "rating": {
        "rate": 8.4,
        "count": 120
        }
    },
    {
        "id": 27,
        "title": "The Robe side table",
        "price": 170.5,
        "description": "I tried to design a supporting structure looking like a robe or some kind of clothes to give the furniture lightness and ease.",
        "category": "Side Tables",
        "image": require("../assets/images/27.jpg"),
        "rating": {
        "rate": 8.4,
        "count": 120
        }
    },
    {
        "id": 28,
        "title": "The Flatfish table",
        "price": 234.3,
        "description": "A more sculptural design this time with a solid wooden base.",
        "category": "Tables",
        "image": require("../assets/images/28.jpeg"),
        "rating": {
        "rate": 8.4,
        "count": 120
        }
    },
    {
        "id": 29,
        "title": "The Peel-all-round coffee table",
        "price": 670.22,
        "description": "This design evolves from three plywood sheets shaping a triangular outline. The table shapes different areas for different needs!",
        "category": "Coffee Table",
        "image": require("../assets/images/29.jpeg"),
        "rating": {
        "rate": 8.4,
        "count": 120
        }
    },
    {
        "id": 30,
        "title": "The Tadashi table",
        "price": 120.5,
        "description": "Visualize within a new scene.",
        "category": "Tables",
        "image": require("../assets/images/30.jpeg"),
        "rating": {
        "rate": 8.4,
        "count": 120
        }
    }
]